[build]
  command = "npm run build"
  publish = "dist/don-francisco/browser"

[build.environment]
  NG_APP_API_URL = "https://donfrancisco-backend.fly.dev/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# =========================
# Allow iframe embeds (Preview modal)
# =========================
[[headers]]
  for = "/*"
  [headers.values]
    # Permitir iframe SOLO desde estos or√≠genes
    Content-Security-Policy = "frame-ancestors 'self' http://localhost:4200 https://jome.uy https://jomeuy.netlify.app;"

    # Headers recomendados
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
