[build]
  command = "npm run build"
  publish = "dist/don-francisco/browser"

[build.environment]
  NG_APP_API_URL = "https://donfrancisco-backend.fly.dev/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# =========================
# Allow iframe embeds (Preview modal)
# =========================
[[headers]]
  for = "/*"
  [headers.values]
    # ✅ Quién puede embeber TU sitio (anti-clickjacking)
    # (esto NO habilita iframes dentro de tu web, solo controla quién te puede embeber a vos)
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self' http://localhost:4200 https://jome.uy https://jomeuy.netlify.app; frame-src 'self' https://bentasca.com https://donfrancisco.uy https://karenbentancor.com https://www.youtube.com https://www.youtube-nocookie.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline'; connect-src 'self' https:;"

    # Headers recomendados
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
